# ===========================================================================
# Trial Configuration: A TEST
# ===========================================================================
# Auto-generated by the dashboard wizard on %d %B %Y
# Edit this file to fine-tune settings.
# ===========================================================================

trial_config <- list(

  # -- Identity --
  code         = "atest",
  name         = "RANDOMISED CONTROL TRIAL",
  short_name   = "A TEST",
  trial_target = 100L,
  category     = "Surgery",

  # -- Design --
  trial_type   = "platform",   # randomised / single_blind / double_blind / observational / single_arm / platform / other
  work_packages = c("WKP1: OBSERVATIONAL HEALTH OUTCOMES", "WKP2: INTERVENTION", "WKP3: MEDICINE"),

  # -- Branding --
  logo_file = NULL,
  colors = list(
    primary   = "#1B4F6B",
    secondary = "#2EC4A5",
    accent    = "#F59E0B"
  ),

  # -- Data paths --
  data_dir = "/Users/georgiamitchell/Documents/Claude/Projects/TONIC Dashboard/BCTU_Clinical_Trials_Dashboard/trials/multiwp/data",
  return_rates_dir = NULL,

  # -- REDCap events --
  redcap_events = list(
    baseline  = "baseline_arm_1",
    discharge = "discharge_arm_1",
    day_30    = NULL,
    day_90    = NULL,
    sub_forms = c("sub_forms_arm_1", "ad_hoc_arm_1")
  ),

  # -- REDCap field mappings --
  redcap_fields = list(
    record_id               = "record_id",
    site_name               = "site_name",
    randomisation_datetime  = "rand_dttm_s",

    operation_date              = NULL,
    operation_datetime          = NULL,
    discharge_date              = NULL,
    age                         = NULL,
    sex                         = NULL,
    ethnicity                   = NULL,

    follow_up_instruments = list(),
    cos_type              = NULL
  ),

  # -- COS type labels (standard defaults) --
  cos_type_labels = c(
    "1" = "Death", "2" = "No Operation", "3" = "Part withdrawal",
    "4" = "Complete withdrawal", "5" = "Lost to follow-up"
  ),

  ethnicity_labels       = NULL,
  white_ethnicity_codes  = NULL,
  target_schedule        = NULL,
  participant_table_layout = NULL,

  projection_defaults = list(
    rate_central = 3.0, rate_optimistic = 4.0, rate_pessimistic = 2.0,
    sites_central = 2.0, sites_optimistic = 3.0, sites_pessimistic = 1.0,
    target_sites = 24
  ),

  report_defaults = list(
    ci      = "GEORGIA MITCHELL",
    sponsor = "UNIVERSITY OF BIRMINGHAM"
  ),

  # -- Feature flags --
  features = list(
    postal_tracking          = FALSE,
    return_rates             = FALSE,
    projections              = TRUE,
    pilot_criteria           = FALSE,
    consort_flow             = FALSE,
    baseline_table           = FALSE,
    participant_questionnaires = TRUE
  )
)

