# =============================================================================
# Report builder (Stage 10) — assembles a self-contained HTML document
# =============================================================================
# Inputs:
#   section_ids — character vector in render order
#   ctx         — list of data the section render functions consume
# Output:
#   character (full HTML document)
# =============================================================================

build_report_html <- function(section_ids, ctx) {
  if (!length(section_ids)) section_ids <- "header"
  body_blocks <- vapply(section_ids, function(id) {
    sec <- report_section_by_id(id)
    if (is.null(sec)) return("")
    tryCatch(sec$render(ctx),
             error = function(e) {
               sprintf("<p style='color:#B91C1C;font-size:12px;'>Failed to render section <code>%s</code>: %s</p>",
                       id, htmltools::htmlEscape(e$message))
             })
  }, character(1))

  body <- paste(body_blocks, collapse = "\n")

  paste0(
"<!DOCTYPE html>
<html><head>
<meta charset='UTF-8'>
<title>Trial report</title>
<style>
  body { font-family: 'Inter', system-ui, sans-serif; color:#0F172A;
         max-width: 880px; margin: 28px auto; padding: 0 24px;
         background:#FAFBFD; }
  h1, h2, h3 { font-family: 'Inter', system-ui, sans-serif; }
  h2 { font-size: 18px; }
  h3 { font-size: 15px; }
  p  { line-height: 1.65; font-size: 13px; }
  table { font-family: 'Inter', system-ui, sans-serif; }
  @media print {
    body { background:#FFFFFF; }
  }
</style>
</head><body>",
body,
"<div style='margin-top:36px;padding-top:14px;border-top:1px solid #EEF2F7;
             font-size:11px;color:#94A3B8;text-align:center;'>",
sprintf("Generated by BCTU Trials Dashboard · %s", format(Sys.Date(), "%d %B %Y")),
"</div>
</body></html>")
}
