# ===========================================================================
# Trial Configuration: TEST
# ===========================================================================
# Auto-generated by the dashboard wizard on %d %B %Y
# Edit this file to fine-tune settings.
# ===========================================================================

trial_config <- list(

  # -- Identity --
  code         = "test",
  name         = "Optimsing post discharge care pathways after acute pancreatitius : evaluation of health service utilisatioin, outcomes",
  short_name   = "Test",
  trial_target = 1000L,
  category     = "Surgery",

  # -- Design --
  trial_type   = "single_arm",   # randomised / single_blind / double_blind / observational / single_arm / other
  arm_export   = "na",   # exported / blinded / na — controls whether arm breakdowns render
  work_packages = c("WPI: Develop conceptual framework for a gold standard post-hospital discharge pathway", "WP2: Explore patient experience of post-hospital discharge care", "WP3: Propose interventions to improve post discharge care"),

  # -- Branding --
  logo_file = NULL,
  colors = list(
    primary   = "#1B4F6B",
    secondary = "#2EC4A5",
    accent    = "#F59E0B"
  ),

  # -- Data paths --
  data_dir = NULL,    # uses trials/<code>/data/
  return_rates_dir = NULL,

  # -- REDCap events --
  redcap_events = list(
    baseline  = "baseline_arm_1",
    discharge = "discharge_arm_1",
    day_30    = NULL,
    day_90    = NULL,
    sub_forms = c("sub_forms_arm_1", "ad_hoc_arm_1")
  ),

  # -- REDCap field mappings --
  redcap_fields = list(
    record_id               = "record_id",
    site_name               = "site_name",
    randomisation_datetime  = "rand_dttm_s",

    operation_date              = NULL,
    operation_datetime          = NULL,
    discharge_date              = NULL,
    age                         = NULL,
    sex                         = NULL,
    ethnicity                   = NULL,

    follow_up_instruments = list(),
    cos_type              = NULL
  ),

  # -- COS type labels (standard defaults) --
  cos_type_labels = c(
    "1" = "Death", "2" = "No Operation", "3" = "Part withdrawal",
    "4" = "Complete withdrawal", "5" = "Lost to follow-up"
  ),

  ethnicity_labels       = NULL,
  white_ethnicity_codes  = NULL,
  target_schedule        = NULL,
  participant_table_layout = NULL,

  projection_defaults = list(
    rate_central = 3.0, rate_optimistic = 4.0, rate_pessimistic = 2.0,
    sites_central = 2.0, sites_optimistic = 3.0, sites_pessimistic = 1.0,
    target_sites = 24
  ),

  report_defaults = list(
    ci      = "Mr Matthew lee",
    sponsor = "University of Birmingham"
  ),

  # -- Feature flags --
  features = list(
    postal_tracking          = FALSE,
    return_rates             = FALSE,
    projections              = TRUE,
    pilot_criteria           = FALSE,
    consort_flow             = TRUE,
    baseline_table           = TRUE,
    participant_questionnaires = TRUE
  )
)

