# ===========================================================================
# Trial Configuration: MULTIWP
# ===========================================================================
# Auto-generated by scripts/generate_multi_wp_dummy.R
# Re-run that script anytime to regenerate the dummy CSV.
# ===========================================================================

trial_config <- list(

  # -- Identity --
  code         = "multiwp",
  name         = "MULTIWP — Multi-work-package Test Trial",
  short_name   = "MULTIWP",
  trial_target = 92L,
  category     = "Surgery",

  # -- Design --
  trial_type    = "platform",   # randomised / single_blind / double_blind / observational / single_arm / platform / other
  work_packages = c("WKP1: Surgery cohort", "WKP2: Recovery cohort", "WKP3: Long-term follow-up"),

  # -- Branding --
  logo_file = NULL,
  colors = list(
    primary   = "#312E81",
    secondary = "#8B5CF6",
    accent    = "#F59E0B"
  ),

  # -- Data paths --
  data_dir = NULL,    # uses trials/<code>/data/
  return_rates_dir = NULL,

  # -- REDCap events --
  redcap_events = list(
    baseline  = "baseline_arm_1",
    discharge = "discharge_arm_1",
    day_30    = NULL,
    day_90    = NULL,
    sub_forms = c("sub_forms_arm_1")
  ),

  # -- REDCap field mappings --
  redcap_fields = list(
    record_id               = "record_id",
    site_name               = "site_name",
    randomisation_datetime  = "rand_dttm_s",

    operation_date          = "surgery_date",
    operation_datetime      = NULL,
    discharge_date          = "discharge_dt",
    age                     = "dem_age",
    sex                     = "dem_sex",
    ethnicity               = "dem_ethnicity",

    follow_up_instruments = list(
      cci     = "cci_complete",
      eq5d    = "eq5d_complete",
      clavien = "clavien_complete"
    ),
    cos_type              = "cos_type"
  ),

  # -- COS type labels (standard defaults) --
  cos_type_labels = c(
    "1" = "Death", "2" = "No Operation", "3" = "Part withdrawal",
    "4" = "Complete withdrawal", "5" = "Lost to follow-up"
  ),

  ethnicity_labels       = NULL,
  white_ethnicity_codes  = NULL,
  target_schedule        = NULL,
  participant_table_layout = NULL,

  projection_defaults = list(
    rate_central = 3.0, rate_optimistic = 4.0, rate_pessimistic = 2.0,
    sites_central = 2.0, sites_optimistic = 3.0, sites_pessimistic = 1.0,
    target_sites = 24
  ),

  report_defaults = list(
    ci      = "Test CI",
    sponsor = "University of Birmingham"
  ),

  # -- Feature flags --
  features = list(
    postal_tracking            = FALSE,
    return_rates               = FALSE,
    projections                = TRUE,
    pilot_criteria             = FALSE,
    consort_flow               = FALSE,
    baseline_table             = TRUE,
    participant_questionnaires = TRUE
  )
)

