# ===========================================================================
# Trial Configuration: PANORAMA
# ===========================================================================
# Auto-generated by the dashboard wizard on %d %B %Y
# Edit this file to fine-tune settings.
# ===========================================================================

trial_config <- list(

  # -- Identity --
  code         = "panorama",
  name         = "Surgery",
  short_name   = "Panorama",
  trial_target = 100L,

  # -- Branding --
  logo_file = NULL,
  colors = list(
    primary           = "#312E81",
    secondary         = "#8B5CF6",
    accent            = "#F59E0B"
  ),

  # -- Data source --
  data_dir = NULL,    # uses trials/<code>/data/

  # -- REDCap events --
  redcap_events = list(
    baseline  = "baseline_arm_1",
    discharge = "discharge_arm_1",
    day_30    = NULL,
    day_90    = NULL,
    sub_forms = c("sub_forms_arm_1", "ad_hoc_arm_1")
  ),

  # -- REDCap field mappings --
  redcap_fields = list(
    record_id               = "record_id",
    site_name               = "site_name",
    randomisation_datetime  = "rand_dttm_s",

    operation_date              = NULL,
    operation_datetime          = NULL,
    discharge_date              = NULL,
    age                         = NULL,
    sex                         = NULL,
    ethnicity                   = NULL,

    follow_up_instruments = list(),
    cos_type              = NULL
  ),

  # -- COS type labels (standard defaults) --
  cos_type_labels = c(
    "1" = "Death", "2" = "No Operation", "3" = "Part withdrawal",
    "4" = "Complete withdrawal", "5" = "Lost to follow-up"
  ),

  ethnicity_labels       = NULL,
  white_ethnicity_codes  = NULL,
  target_schedule        = NULL,
  participant_table_layout = NULL,

  projection_defaults = list(
    rate_central = 3.0, rate_optimistic = 4.0, rate_pessimistic = 2.0,
    sites_central = 2.0, sites_optimistic = 3.0, sites_pessimistic = 1.0,
    target_sites = 24
  ),

  report_defaults = list(
    ci      = "Matthew Lee",
    sponsor = "University of Birmingham"
  ),

  # -- Feature flags --
  features = list(
    postal_tracking  = FALSE,
    return_rates     = FALSE,
    projections      = TRUE,
    pilot_criteria   = TRUE,
    consort_flow     = TRUE,
    baseline_table   = TRUE
  )
)

